---

- name: "Install MySQL"
  action: apt pkg=$item state=installed
  with_items:
   - mysql-server

- name: "Start service MySQL"
  service: name=mysql state=started enabled=true
  ignore_errors: yes


